#!/bin/bash

# This will setup all the env vars we need for Apollo to test with

export OMP_NUM_THREADS=36
export OMP_WAIT_POLICY="active"
export OMP_PROC_BIND="close"
export OMP_PLACES="cores"
export APOLLO_TRACE_CSV_FOLDER_SUFFIX="-test"
export APOLLO_COLLECTIVE_TRAINING=0 
export APOLLO_LOCAL_TRAINING=1 
export APOLLO_RETRAIN_ENABLE=0 
export APOLLO_STORE_MODELS=0
export APOLLO_TRACE_CSV=0
export APOLLO_SINGLE_MODEL=0 
export APOLLO_REGION_MODEL=1 
export APOLLO_GLOBAL_TRAIN_PERIOD=10000
export APOLLO_POLICY_MODEL="Static,policy=0"
export APOLLO_ENABLE_PERF_CNTRS=1
export APOLLO_PERF_CNTRS_MLTPX=0
export APOLLO_PERF_CNTRS="PAPI_DP_OPS,PAPI_TOT_INS" 